### ISSUE TITLE
Investigate using kaniko to build docker images

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-docker#16]
Rather than using root access to the Docker daemon socket, try to use [Kaniko](https://github.com/GoogleContainerTools/kaniko).

**Comment by ddgenome** [comment]
We might want to keep the current behavior and test for the existence of `/kaniko` in the image and use it if available. If kaniko is not present, test for the Docker environment variables and socket and use them if you can. Otherwise, fail.

**Comment by ddgenome** [comment]
Here's another option https://github.com/uber/makisu

**Comment by cdupuis** [comment]
Added via PR #40
