### ISSUE TITLE
//FROM/image/name not working for simple, but valid docker images

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/sdm-pack-docker#51]
Trying to extract a docker image with just a name (no tag, no repo)

```
FROM nginx

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY resources/public /usr/share/nginx/html

EXPOSE 8080
```

like this:

```
        const imageName: string[] = await astUtils.findValues(
            p, DockerFileParser, "docker/Dockerfile", "//FROM/image/name");
```

does not currently work.

**Comment by johnsonr** [comment]
Are you sure you'll looking in the right place for the Dockerfile? Otherwise you will get nothing back.

I upgraded the `dockerfile-ast` library and added a test and this works.

**Comment by slimslenderslacks** [comment]
I'll have to upgrade to 2.0 before I can evaluate.  Working on that.

**Comment by slimslenderslacks** [comment]
This is all working with an upgrade to 2.0
